const PRESETS = [
  { key: "coast", label: "雾港海岸（CoC 风格）",
    text: "1920 年代一片东临大海的雾气海岸，南北约一千公里。西部是南北走向的老山脉「鸦脊山」，常年西风从山那边吹来；东北有东西走向的丘陵「寒丘」。至少三条大河入海，内陆至少有两个湖。东部河口有港口「灰锚港」；东南海边有渔村「盐沼村」；中部河畔有「磨坊镇」；南部河边有渡口镇「渡鸦渡」；西部山脚有「黑松村」；西南湖边有「静湖庄」；北部有小城「北钟镇」；东北丘陵下有要塞「石冢堡」。",
    spec: { name: "雾港海岸", seed: 1926, ocean_side: "E", wind_from: "W",
      mountains: [{ name: "鸦脊山", region: "W", orientation: "NS" }, { name: "寒丘", region: "NE", orientation: "EW" }],
      min_major_rivers: 3, min_lakes: 2,
      settlements: [
        { name: "灰锚港", type: "port", region: "E", requires: ["coast", "river_mouth"] },
        { name: "盐沼村", type: "village", region: "SE", requires: ["coast"] },
        { name: "磨坊镇", type: "town", region: "C", requires: ["on_river"] },
        { name: "渡鸦渡", type: "town", region: "S", requires: ["on_river"] },
        { name: "黑松村", type: "village", region: "W", requires: ["near_mountain"] },
        { name: "静湖庄", type: "village", region: "SW", requires: ["lakeside"] },
        { name: "北钟镇", type: "city", region: "N", requires: [] },
        { name: "石冢堡", type: "fortress", region: "NE", requires: ["near_mountain"] },
      ] } },
  { key: "kingdom", label: "双河王国（奇幻）",
    text: "南临大海的王国，疆域约一千公里见方。北部横亘东西走向的「霜冠山脉」，冷风从北方吹来；东部有南北走向的「赤岩岭」。至少四条大河向南入海。王都「白塔城」在中部河畔；北部山下有要塞「铁门堡」；东部山口有关隘「狼口关」；南部河口有港口「潮湾」；东南海岸有港口「灰羽港」；东北有城镇「琥珀集」；西部有村庄「麦浪村」；西南有河边村庄「芦苇渡」。",
    spec: { name: "双河王国", seed: 4417, ocean_side: "S", wind_from: "N",
      mountains: [{ name: "霜冠山脉", region: "N", orientation: "EW" }, { name: "赤岩岭", region: "E", orientation: "NS" }],
      min_major_rivers: 4, min_lakes: 0,
      settlements: [
        { name: "白塔城", type: "city", region: "C", requires: ["on_river"] },
        { name: "铁门堡", type: "fortress", region: "N", requires: ["near_mountain"] },
        { name: "狼口关", type: "fortress", region: "E", requires: ["near_mountain"] },
        { name: "潮湾", type: "port", region: "S", requires: ["coast", "river_mouth"] },
        { name: "灰羽港", type: "port", region: "SE", requires: ["coast"] },
        { name: "琥珀集", type: "town", region: "NE", requires: [] },
        { name: "麦浪村", type: "village", region: "W", requires: [] },
        { name: "芦苇渡", type: "village", region: "SW", requires: ["on_river"] },
      ] } },
  { key: "island", label: "潮汐群岛主岛（岛屿）",
    text: "一座被海包围的大岛。中部有南北走向的火山脊「灰烬脊」，东风从海上吹来。至少三条大河，一个火山湖。西岸有港口「落潮港」，东岸有港口「晨雾港」，北部有渔村「鲸骨村」，中部山脚有修道院村落「钟隐村」，南部河边有「稻田镇」。",
    spec: { name: "潮汐群岛", seed: 3031, ocean_side: "all", wind_from: "E",
      mountains: [{ name: "灰烬脊", region: "C", orientation: "NS" }],
      min_major_rivers: 3, min_lakes: 1,
      settlements: [
        { name: "落潮港", type: "port", region: "W", requires: ["coast", "river_mouth"] },
        { name: "晨雾港", type: "port", region: "E", requires: ["coast"] },
        { name: "鲸骨村", type: "village", region: "N", requires: ["coast"] },
        { name: "钟隐村", type: "village", region: "C", requires: ["near_mountain"] },
        { name: "稻田镇", type: "town", region: "S", requires: ["on_river"] },
      ] } },
  { key: "impossible", label: "内陆港口（矛盾需求）",
    text: "一片四面不靠海的内陆高原。中部有一条东西走向的「断碑岭」，风从西边来。要有两条大河。东部要有一个港口城市「无潮港」，南部有靠山的村子「石屋村」，西部有河边集镇「驼铃集」。",
    spec: { name: "断碑高原", seed: 808, ocean_side: "none", wind_from: "W",
      mountains: [{ name: "断碑岭", region: "C", orientation: "EW" }],
      min_major_rivers: 2, min_lakes: 0,
      settlements: [
        { name: "无潮港", type: "port", region: "E", requires: ["coast"] },
        { name: "石屋村", type: "village", region: "S", requires: ["near_mountain"] },
        { name: "驼铃集", type: "town", region: "W", requires: ["on_river"] },
      ] } },
];
if (typeof module !== "undefined") module.exports = { PRESETS };
